USE [SNTBROKER_SIE_MEJORADA]
GO

/****** Object:  Table [dbo].[ACCIONESEEUU_V2]    Script Date: 22/02/2021 17:57:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ALERTAS_V3](
	[CLAVE] [VARCHAR] (10) NOT NULL,
	[IDEMPRESA] [INT] NOT NULL,
	[HORA_DISCRETIZADA] [VARCHAR] (5) NOT NULL,
	[PORC_DESFASE] [INT] NOT NULL,
	[VOL_MEDIO] [INT] NOT NULL,
	[VOLUMEN] [INT] NOT NULL,
	[FECHA] [SMALLDATETIME] NOT NULL
) ON [PRIMARY]
GO

INSERT INTO [dbo].[ALERTAS_V3]
SELECT 
	CONVERT(VARCHAR(10),SUBSTRING(ALERTA,7, PATINDEX('%/%',ALERTA)-7)) AS CLAVE,
	CONVERT(INT, SUBSTRING(ALERTA, PATINDEX('%IDEMPRESA=%',ALERTA)+10,
			  CHARINDEX('/',ALERTA,PATINDEX('%IDEMPRESA=%',ALERTA)+10)-PATINDEX('%IDEMPRESA=%',ALERTA)-10)) AS IDEMPRESA,
	CONVERT(VARCHAR(5), SUBSTRING(ALERTA, PATINDEX('%HORA DISCRETIZADA=%',ALERTA)+18,
			  CHARINDEX('/',ALERTA,PATINDEX('%HORA DISCRETIZADA=%',ALERTA)+18)-PATINDEX('%HORA DISCRETIZADA=%',ALERTA)-18)) AS HORA_DISCRETIZADA,
	CONVERT(INT, SUBSTRING(ALERTA, PATINDEX('%PORC DESFASE=%',ALERTA)+13,
			  CHARINDEX('/',ALERTA,PATINDEX('%PORC DESFASE=%',ALERTA)+13)-PATINDEX('%PORC DESFASE=%',ALERTA)-13)) AS PORC_DESFASE,
	CONVERT(INT, SUBSTRING(ALERTA, PATINDEX('%VOL MEDIO=%',ALERTA)+10,
			  CHARINDEX('/',ALERTA,PATINDEX('%VOL MEDIO=%',ALERTA)+10)-PATINDEX('%VOL MEDIO=%',ALERTA)-10)) AS VOL_MEDIO,
	CONVERT(INT, SUBSTRING(ALERTA, PATINDEX('%VOLUMEN=%',ALERTA)+8,
			  LEN(ALERTA)-PATINDEX('%VOLUMEN=%',ALERTA)-7)) AS VOLUMEN,
	CONVERT(SMALLDATETIME, FECHA) AS FECHA
FROM [SNTBROKER_SIE].[dbo].[ALERTAS_V2];
