USE [SNTBROKER_SIE_MEJORADA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COTIZACIONES_DIARIAS_TEMP_V3](
 [IDEMPRESA] [smallint] NOT NULL,
 [FECHA] [smalldatetime] NOT NULL,
 [ULT] [float] (15) NOT NULL
) ON [PRIMARY]
GO

INSERT INTO [SNTBROKER_SIE_MEJORADA].[dbo].[COTIZACIONES_DIARIAS_TEMP_V3]
SELECT
 convert(smallint, IDEMPRESA) as IDEMPRESA,
 TRY_PARSE(CONCAT(MES,'-',DIA,'-',ANNIO) AS DATETIME USING 'en-us') AS FECHA,
 convert(float(15), ULT) as ULT
FROM [SNTBROKER_SIE].[dbo].[COTIZACIONES_DIARIAS_TEMP_V2]
