/****** Object:  Table [dbo].[EMPRESAS_V3]    Script Date: 22/02/2021 17:55:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [SNTBROKER_SIE]
GO

UPDATE EMPRESAS_V2 SET IdSector = 0 WHERE IdSector IS NULL;

USE [SNTBROKER_SIE_MEJORADA]
GO

CREATE TABLE [dbo].[EMPRESAS_V3](
	[ID_EMPRESA] [INT] NOT NULL,
	[CLAVE] [VARCHAR] (18) NOT NULL,
	[ISIN] [VARCHAR] (12) NOT NULL,
	[NOMBRE] [VARCHAR] (35) NOT NULL,
	[ID_MERCADO] [INT] NOT NULL,
	[ID_SECTOR] [INT] NULL,
	[FECHA_INSERCION] [SMALLDATETIME] NOT NULL
) ON [PRIMARY]
GO

INSERT INTO [dbo].[EMPRESAS_V3]
select
	convert(INT,IdEmpresa) as ID_EMPRESA,
	convert(VARCHAR (18),Clave) as CLAVE,
	convert(VARCHAR (12),Isin) as ISIN,
	convert(VARCHAR (35),Nombre) as NOMBRE,
	convert(INT,IdMercado) as ID_MERCADO,
	convert(INT,IdSector) as ID_SECTOR,
	convert(SMALLDATETIME,FechaInsercion) as FECHA_INSERCION
from [SNTBROKER_SIE].[dbo].[EMPRESAS_V2];
