USE [SNTBROKER_SIE_MEJORADA]
GO

/****** Object:  Table [dbo].[MATRIZ1_TEMP_v2]    Script Date: 22/02/2021 17:55:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MATRIZ1_TEMP_v3](
	[MATRIZ1] [CHAR] (78) NOT NULL
) ON [PRIMARY]
GO

INSERT INTO [dbo].[MATRIZ1_TEMP_v3]
SELECT
	CONVERT(CHAR(78),MATRIZ1) AS MATRIZ1
FROM [SNTBROKER_SIE].[dbo].[MATRIZ1_TEMP_v2]
