USE [SNTBROKER_SIE_MEJORADA]
GO

/****** Object:  Table [dbo].[PATRONES_v2]    Script Date: 22/02/2021 17:57:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PATRONES_V3](
	[PATRON] [NVARCHAR] (15) NOT NULL
) ON [PRIMARY]
GO

INSERT INTO [dbo].[PATRONES_V3]
SELECT
	CONVERT(NVARCHAR(15),IdPatron) AS PATRON
FROM [SNTBROKER_SIE].[dbo].[PATRONES_v2];
GO

ALTER TABLE PATRONES_V3
  ADD ID_PATRON INT IDENTITY(1,1) NOT NULL

  SELECT * FROM PATRONES_V3
