USE [SNTBROKER_SIE_MEJORADA]
GO

/****** Object:  Table [dbo].[ULTDIF_ARBOLDECISION_TEMP_v2]    Script Date: 24/02/2021 21:40:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ULTDIF_ARBOLDECISION_TEMP_v3](
	[ID_EMPRESA] [SMALLINT] NOT NULL,
	[CLAVE] [VARCHAR](10) NOT NULL,
	[ID_PATRON] [SMALLINT] NOT NULL,
	[NUMERO] [smallint] NOT NULL
) ON [PRIMARY]
GO

INSERT INTO [dbo].[ULTDIF_ARBOLDECISION_TEMP_v3]
SELECT
	CONVERT(SMALLINT, IDEMPRESA) AS ID_EMPRESA,
	CONVERT(VARCHAR(10), CLAVE) AS CLAVE,
	CONVERT(SMALLINT, ID_PATRON) AS ID_PATRON,
	CONVERT(SMALLINT, CONVERT(REAL, NUMERO)) AS NUMERO
FROM [SNTBROKER_SIE].[dbo].[ULTDIF_ARBOLDECISION_TEMP_v2] A, 
	 [SNTBROKER_SIE_MEJORADA].[dbo].[PATRONES_V3] B 
WHERE B.PATRON = A.IDPATRON;
